version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: atedzi/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
      - ./docs:/usr/share/nginx/html/docs

  frontend:
    env_file: .env
    image: atedzi/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: atedzi/foodgram_gateway
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      # - static:/static
      # - media:/media
      # - ./docs:/usr/share/nginx/html/docs

      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/media