version: '3'

volumes:
  db_volume:
  static_volume:
  media:

services:

  db:
    image: postgres:13.10
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: atedzi/foodgram_backend
    restart: always
    volumes:
    #  - static_volume:/app/static/
     - static_volume:/backend_static
     - media:/app/media/
    env_file:
     - ./.env

  frontend:
    image: atedzi/foodgram_frontend
    env_file: ./.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      # - ../frontend/:/app/result_build/
      - static:/frontend_static

  gateway:
    image: atedzi/foodgram_gateway
    env_file: ./.env
    volumes:
      - static_volume:/staticfiles/
      - media:/media
    ports:
      - 6000:80

  # nginx:
  #   container_name: nginx
  #   image: nginx:1.19.3
  #   ports:
  #     - "6000:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/:/usr/share/nginx/html/api/docs/
  #     - static_volume:/var/html/static/
  #     - media:/var/html/media/
  #   restart: always
  #   depends_on:
  #     - backend
