version: '3' 

volumes: 
  pg_data: 
  static_volume: 
  media: 

services:

  db: 
    image: postgres:13.10 
    volumes: 
      - pg_data:/var/lib/postgresql/data/ 
    env_file: 
      - ./.env 

  backend: 
    container_name: backend 
    image: atedzi/foodgram_backend 
    restart: always 
    volumes: 
     - static_volume:/app/static/ 
     - media:/app/media/ 
    depends_on: 
     - db 
    env_file: 
     - ./.env 

  frontend: 
    image: atedzi/foodgram_frontend 
    env_file: ./.env 
    command: cp -r /app/build/. /frontend_static/ 
    volumes: 
      - static_volume:/frontend_static 
    depends_on: 
      - db 

  nginx: 
    container_name: nginx 
    image: nginx:1.19.3 
    ports: 
      - "6000:80" 
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - ../frontend/build:/usr/share/nginx/html/ 
      - ../docs/:/usr/share/nginx/html/api/docs/ 
      - static_volume:/var/html/static/ 
      - media:/var/html/media/ 
    depends_on: 
      - backend