# file docker-compose.yml
version: '3.3'
services:

  db:
    container_name: db
    image: postgres:13.10
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend
    image: val911/foodgram_backend
    restart: always
    volumes:
     - static_volume:/app/static/
     - media:/app/media/
    depends_on:
     - db
    env_file:
     - .env
    ports:
     - "6000:6000"

  frontend:
    container_name: frontend
    image: val911/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media:/var/html/media/

volumes:
  static_volume:
  media:
  db_volume:
