# Generated by Django 3.2 on 2023-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230921_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#18c4e8', max_length=7, unique=True, verbose_name='Цвет (HEX code)'),
        ),
    ]
